version: '3.8'
services:
  
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2483
      POSTGRES_DB: pix
    ports:
      - 5439:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  
  pix:
    image: pix
    container_name: pix
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - migrate
    environment:
      - DATABASE__HOST=postgres
      - DATABASE__PORT=5432
      - DATABASE__USERNAME=postgres
      - DATABASE__PASSWORD=2483
      - DATABASE__NAME=pix
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5045/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  migrate:
    image: pix-migrate
    container_name: migrate
    build:
      context: .
      dockerfile: Dockerfile.migrations
    environment:
      - DATABASE__HOST=postgres
      - DATABASE__PORT=5432
      - DATABASE__USERNAME=postgres
      - DATABASE__PASSWORD=postgres
      - DATABASE__NAME=pix
    depends_on:
      - postgres

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.12-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  postgres-volume:
  rabbitmq-volume: